Pal 650 resource service redis persistence
gchq/Palisade-integration-tests pull request #73
Opened 2020-08-25 11:01 UTC by dev930018

2020-08-28 08:03 UTC, pd104923 requested changes

2020-08-28 08:03 UTC, pd104923 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ResourceComponentTest.java
> +@ActiveProfiles("h2")
Why are we using h2 in tests when this is not used for the actual service?

2020-08-28 12:03 UTC, dev930018 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ResourceComponentTest.java
> +@ActiveProfiles("h2")
Previously h2 was default.
Can now choose between h2 and redis, h2 should be faster to spin up for small tests

2020-09-03 13:34 UTC, developer01189998819991197253 commented on resource-service-integration/src/test/resources/application.yaml
> +# Copyright 2019 Crown Copyright
reverted

2020-09-04 10:16 UTC, developer01189998819991197253 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/RedisPersistenceTest.java
> +import static org.junit.Assert.assertThat;
new tests should be written in Junit5, using AssertJ

2020-09-04 10:20 UTC, developer01189998819991197253 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ScenarioPersistenceTest.java
> -/*
Why are the majority of changes here just deleting the contents and replacing them again?

2020-09-04 10:22 UTC, developer01189998819991197253 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/config/ResourceTestConfiguration.java
> -/*
This file has no changes in

2020-09-04 10:26 UTC, developer01189998819991197253 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ScenarioPersistenceTest.java
> +@ActiveProfiles("h2")
This seems to be the only addition to this file, why is the whole thing marked as deleted and readded??

2020-09-04 10:26 UTC, kg981167224 submitted a review, later dismissed

2020-09-04 10:26 UTC, kg981167224 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ResourceComponentTest.java
> +@ActiveProfiles("h2")
I would also question if we want to keep H2? Happy if that's what we want to do, probably just worth asking the question if there is no prod use for it.

If startup time is an usse we could look at https://github.com/caryyu/spring-embedded-redis-server?

2020-09-04 10:26 UTC, kg981167224 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ScenarioPersistenceTest.java
> -/*
Diff has made a bit of a hash of this file, can't easily see the changes.

2020-09-04 10:27 UTC, developer01189998819991197253 commented on resource-service-integration/README.md
> -<!---
There have been no changes made to this file

2020-09-04 10:27 UTC, developer01189998819991197253 requested changes
A bunch of files have no changes
New tests should be written in Junit5

2020-09-04 11:05 UTC, dev930018 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ResourceComponentTest.java
> +@ActiveProfiles("h2")
We're already using embedded-redis for the redis tests.
I think it's just a case of how we're going to support a JVM-only deployment, if at all...
Obviously kafka will always be needed, but it at least makes sense to keep the H2 support here for now, until we decide if we want to drop it later.

2020-09-04 11:06 UTC, dev930018 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ScenarioPersistenceTest.java
> +@ActiveProfiles("h2")
Line endings

2020-09-04 11:07 UTC, dev930018 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ScenarioPersistenceTest.java
> -/*
Line endings

2020-09-04 12:03 UTC, dev930018 commented on resource-service-integration/README.md
> -<!---
Line endings

2020-09-04 12:03 UTC, dev930018 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/config/ResourceTestConfiguration.java
> -/*
Line endings

2020-09-04 14:44 UTC, developer01189998819991197253 submitted a review, later dismissed

2020-09-04 14:51 UTC, ac74475 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ResourceComponentTest.java
> +@ActiveProfiles("h2")
I agree lets keep H2 in the tests for now, but we may loop back round to the broader question of whether we really need H2 for the JVM only deployments. At the moment it isn't doing any harm having it in

2020-09-04 15:01 UTC, ac74475 requested changes

2020-09-04 15:01 UTC, ac74475 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ScenarioPersistenceTest.java
> +@ActiveProfiles("h2")
I would have expected a similar set of tests to these but targeting the redis active profile, the same as we do for the unit and configuration tests

2020-09-04 15:30 UTC, developer01189998819991197253 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ScenarioPersistenceTest.java
> +@ActiveProfiles("h2")
Theres a RedisPersistenceTest which targets redis, do you require further tests?

2020-09-04 16:50 UTC, ac74475 approved these changes

2020-09-04 16:52 UTC, ac74475 commented on resource-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/resource/ScenarioPersistenceTest.java
> +@ActiveProfiles("h2")
nope happy now I have realised the differences

2020-09-08 12:24 UTC, merged