Pal 649 policy service redis
gchq/Palisade-integration-tests pull request #74
Opened 2020-08-28 10:55 UTC by pd104923

2020-09-03 07:58 UTC, dbz120896 requested changes

2020-09-03 07:58 UTC, dbz120896 commented on policy-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/policy/RedisPolicyCachingTest.java
> +            assertThat(policy).isNotNull();
Should this be `.isPresent()`?

2020-09-03 08:32 UTC, developer01189998819991197253 commented on policy-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/policy/RedisPolicyCachingTest.java
> +            assertThat(policy).isNotNull();
.isPresent is the Junit way of doing not null checks using just Junit, and assertThat(x).isNotNull is the assertJ way which we agreedupon in the high level test strategy

2020-09-03 09:07 UTC, dbz120896 commented on policy-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/policy/RedisPolicyCachingTest.java
> +            assertThat(policy).isNotNull();
But, doesn't `cacheProxy.getPolicy(resource);` always return a non-null optional? So, policy will always be non-null.

2020-09-04 07:19 UTC, dbz120896 submitted a review, later dismissed

2020-09-04 11:03 UTC, dev930018 requested changes

2020-09-04 11:03 UTC, dev930018 commented on policy-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/policy/RedisPolicyCachingTest.java
> +        assertThat(returnedPolicy.get()).isNotNull();
There should be no need to test Optional.get() is not null, but rather should test Optional.isPresent()

2020-09-04 11:03 UTC, dev930018 commented on policy-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/policy/CaffeinePolicyCachingTest.java
> +            assertThat(policy).isNotNull();
Ditto some optional isPresent check over isNotNull

2020-09-04 14:33 UTC, developer01189998819991197253 commented on policy-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/policy/config/RedisTestConfiguration.java
> +@EnableAutoConfiguration
I believe so, it was implemeted in the user service redis testing also

2020-09-04 15:07 UTC, dev930018 approved these changes

2020-09-04 15:23 UTC, ac74475 approved these changes

2020-09-07 09:59 UTC, dev930018 approved these changes
Aside from possibly moving to Palisade-services/policy-service/src/component-test

2020-09-07 11:28 UTC, developer01189998819991197253 commented
> 
> 
> Aside from possibly moving to Palisade-services/policy-service/src/component-test

For existing tickets we can leave them as is, in the future we will transition

2020-09-07 13:22 UTC, developer01189998819991197253 approved these changes

2020-09-08 08:02 UTC, ac74475 approved these changes

2020-09-08 11:17 UTC, merged