PAL-411 attribute-masking-service integration tests
gchq/Palisade-integration-tests pull request #75
Opened 2020-08-28 12:18 UTC by dev930018

2020-09-01 09:51 UTC, pd104923 requested changes

2020-09-01 09:51 UTC, pd104923 commented on attribute-masking-service-integration/pom.xml
> +  ~ Copyright 2019 Crown Copyright
```suggestion
  ~ Copyright 2020 Crown Copyright
```

2020-09-01 09:51 UTC, pd104923 commented on attribute-masking-service-integration/src/test/resources/application.yaml
> +    name: audit-service
```suggestion
    name: attribute-masking-service
```

2020-09-01 09:51 UTC, pd104923 commented on attribute-masking-service-integration/src/test/resources/application.yaml
> +  port: 8088
Have we decided if there is going to be a specific port numbers for these services? This one is the same as the audit-service so would need to be changed.

2020-09-01 13:53 UTC, pd104923 approved these changes

2020-09-03 14:56 UTC, m78233 commented on attribute-masking-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/attributemask/AttributeMaskingServiceComponentTest.java
> +class AttributeMaskingServiceComponentTest {
Suggest making class public.

2020-09-03 15:08 UTC, m78233 commented on attribute-masking-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/attributemask/AttributeMaskingServiceComponentTest.java
> +    private TestRestTemplate restTemplate;
Think that there still needs to be a test for the Controller.  Managed to find one ok (ish) article on the distinction of using TestRestTemplate and MockMvc in testing.  
https://spring.io/blog/2012/11/12/spring-framework-3-2-rc1-spring-mvc-test-framework.  Basic is that the MockMvc is for the server-side and TestRestTemplate is for the client-side.

2020-09-03 15:18 UTC, m78233 commented on attribute-masking-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/attributemask/AttributeMaskingServiceComponentTest.java
> +class AttributeMaskingServiceComponentTest {
We have to create a class in one repo and related Component test in another repo.  It is a scenario that can easily create problems if the two get out of sync.  Think that it should in the same repo as the code that is being tested.

2020-09-03 15:25 UTC, m78233 reviewed
Suggestion, change ticket for just the  Rest endpoint.  Ticket refers to Kafka Consumer and Producer and Contract test be put on another ticket.

2020-09-04 10:54 UTC, dev930018 commented on attribute-masking-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/attributemask/AttributeMaskingServiceComponentTest.java
> +class AttributeMaskingServiceComponentTest {
Junit 5 and sonarqube take the stance that test classes should be package-private

2020-09-04 10:55 UTC, dev930018 commented on attribute-masking-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/attributemask/AttributeMaskingServiceComponentTest.java
> +class AttributeMaskingServiceComponentTest {
Will be covered in a future ticket

2020-09-04 12:41 UTC, dev930018 commented on attribute-masking-service-integration/src/test/java/uk/gov/gchq/palisade/integrationtests/attributemask/AttributeMaskingServiceComponentTest.java
> +    private TestRestTemplate restTemplate;
I feel in this case there isn't much to gain from these sorts of tests - the application functionality just isn't in here yet, and it forces us back to JUnit 4 methods afaik

2020-09-09 14:53 UTC, closed without merging