Pal 544 k8s end to end
gchq/Palisade-integration-tests pull request #79
Opened 2020-09-25 10:27 UTC by pd104923

2020-09-28 12:10 UTC, m78233 submitted a review, later dismissed

2020-09-28 17:11 UTC, dev930018 submitted a review, later dismissed

2020-09-30 15:30 UTC, ac74475 requested changes

2020-09-30 15:30 UTC, ac74475 commented on Jenkinsfile
> +                                        sh "bash deployment/aws-k8s/example-model/verify.sh ${HELM_DEPLOY_NAMESPACE}"
delete namespace if it succeeded and it is a feature branch. We will keep it up if it fails so developers can debug

2020-09-30 16:47 UTC, pd104923 commented on Jenkinsfile
> +                                        sh "bash deployment/aws-k8s/example-model/verify.sh ${HELM_DEPLOY_NAMESPACE}"
Added `kubectl delete ns ${HELM_DEPLOY_NAMESPACE}` if successful

2020-10-01 07:59 UTC, ac74475 requested changes

2020-10-01 07:59 UTC, ac74475 commented on Jenkinsfile
> +                                        sh "kubectl delete ns ${HELM_DEPLOY_NAMESPACE}"
```suggestion
                                        if (FEATURE_BRANCH == "true") {
                                            sh "kubectl delete ns ${HELM_DEPLOY_NAMESPACE}"
                                        }
```

2020-10-01 08:33 UTC, ac74475 approved these changes

2020-10-01 08:33 UTC, pd104923 commented on Jenkinsfile
> +                                        sh "kubectl delete ns ${HELM_DEPLOY_NAMESPACE}"
Updated

2020-10-01 11:21 UTC, merged